[package]
name = "marstui-audio"
version = "2.2.0"
edition = "2024"

[dependencies]
tui = "0.19.0"
crossterm = "0.23"
mpris = "2.0.1"
zbus = "5.6.0"
serde = { version = "1.0.216", features = ["derive"] }
dirs = "6.0.0"
toml = "0.5.11"